GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name":"cael",
    "password":"QP07dz93UKa6"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "name":"admin",
    "password":"admin"
}
