name: server

on:
  # workflow_run:
  #   workflows: ["docker"]
  #   types:
  #     - completed
  workflow_dispatch:

jobs:
  server:
    runs-on: self-hosted
    steps:
      - name: SSH Action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            cd /home/$USER/Projects/Punch
            git pull
            docker-compose down
            docker rmi mraddict063/punch
            docker-compose up -d
