name: server

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Deploy-To-Server:
    runs-on: self-hosted
    steps:
      - name: SSH Action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            cd /home/$USER/Projects/Punch
            git pull
            docker-compose down
            docker build -t mraddict063/punch --rm .
            docker rmi $(docker images --filter "dangling=true" -q --no-trunc)
            docker-compose up -d
